apiVersion: apps/v1
kind: Deployment
metadata:
  name: finetune-controller
  namespace: datatunerx-dev
  labels:
    datatunerx.io/component: finetune
spec:
  selector:
    matchLabels:
      datatunerx.io/component: finetune
  replicas: 1
  template:
    metadata:
      labels:
        datatunerx.io/component: finetune
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: METRICS_EXPORT_ADDRESS
            value: http://10.33.1.10:30722
          - name: STORAGE_PATH
            value: s3://datatunerx/tuning?endpoint_override=http://10.33.1.10:32575
        image: 10.33.1.11:9090/datatunerx/finetune-controller:v0.0.1
        name: manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: finetune-controller
      terminationGracePeriodSeconds: 10

