apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: finetune-controller
    app.kubernetes.io/part-of: finetune-controller
    app.kubernetes.io/managed-by: kustomize
  name: finetune-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: finetune-controller-role
subjects:
- kind: ServiceAccount
  name: finetune-controller
  namespace: datatunerx-dev
